CREATE (ECU:Container {name: 'ECU'})	
CREATE (TCU:Container {name: 'TCU'})	
CREATE (Server:Container {name: 'Server'})	
	
	
	
CREATE (ECU_sum:Node {name: 'SW Update manager'})	CREATE (ECU)-[:contains]->(ECU_sum)
CREATE (ECU_ds:Node {name: 'Diagnosis Service'})	CREATE (ECU)-[:contains]->(ECU_ds)
CREATE (ECU_ivc:Node {name: 'Invehicle Communication'})	CREATE (ECU)-[:contains]->(ECU_ivc)
CREATE (ECU_ssu:Node {name: 'Secure SW Update'})	CREATE (ECU)-[:contains]->(ECU_ssu)
CREATE (ECU_sb:Node {name: 'Secure Boot'})	CREATE (ECU)-[:contains]->(ECU_sb)
CREATE (ECU_soc:Node {name: 'Secure Onboard Communication'})	CREATE (ECU)-[:contains]->(ECU_soc)
CREATE (ECU_sa:Node {name: 'Secure Access'})	CREATE (ECU)-[:contains]->(ECU_sa)
CREATE (ECU_cl:Node {name: 'Cryptolib'})	CREATE (ECU)-[:contains]->(ECU_cl)
CREATE (ECU_aes1:Node {name: 'AES128 CMAC'})	CREATE (ECU)-[:contains]->(ECU_aes1)
CREATE (ECU_rsa:Node {name: 'RSA2048'})	CREATE (ECU)-[:contains]->(ECU_rsa)
CREATE (ECU_hmac:Node {name: 'HMAC SHA256'})	CREATE (ECU)-[:contains]->(ECU_hmac)
CREATE (ECU_aes2:Node {name: 'AES128 ECB'})	CREATE (ECU)-[:contains]->(ECU_aes2)
CREATE (ECU_k1:Node {name: 'K_1'})	CREATE (ECU)-[:contains]->(ECU_k1)
CREATE (ECU_k5:Node {name: 'K_5'})	CREATE (ECU)-[:contains]->(ECU_k5)
CREATE (ECU_k_pb_2:Node {name: 'K_pb_2'})	CREATE (ECU)-[:contains]->(ECU_k_pb_2)
CREATE (ECU_k_pr_2:Node {name: 'K_pr_2'})	CREATE (ECU)-[:contains]->(ECU_k_pr_2)
CREATE (ECU_k3:Node {name: 'K_3'})	CREATE (ECU)-[:contains]->(ECU_k3)
CREATE (ECU_k4:Node {name: 'K_4'})	CREATE (ECU)-[:contains]->(ECU_k4)
	
	
CREATE (TCU_ssu:Node {name: 'Secure SW Update'})	CREATE (TCU)-[:contains]->(TCU_ssu)
CREATE (TCU_sb:Node {name: 'Secure Boot'})	CREATE (TCU)-[:contains]->(TCU_sb)
CREATE (TCU_soc:Node {name: 'Secure Onboard Communication'})	CREATE (TCU)-[:contains]->(TCU_soc)
CREATE (TCU_src:Node {name: 'Secure Remote Communication'})	CREATE (TCU)-[:contains]->(TCU_src)
CREATE (TCU_sa:Node {name: 'Secure Access'})	CREATE (TCU)-[:contains]->(TCU_sa)
CREATE (TCU_tls:Node {name: 'TLS1.2'})	CREATE (TCU)-[:contains]->(TCU_tls)
CREATE (TCU_aes256:Node {name: 'AES256 GCM'})	CREATE (TCU)-[:contains]->(TCU_aes256)
CREATE (TCU_cl:Node {name: 'Cryptolib'})	CREATE (TCU)-[:contains]->(TCU_cl)
CREATE (TCU_cert:Node {name: 'Certificate'})	CREATE (TCU)-[:contains]->(TCU_cert)
CREATE (TCU_aes128_1:Node {name: 'AES128 ECB'})	CREATE (TCU)-[:contains]->(TCU_aes128_1)
CREATE (TCU_k_pb_10:Node {name: 'K_pb_10'})	CREATE (TCU)-[:contains]->(TCU_k_pb_10)
CREATE (TCU_dh:Node {name: 'DH'})	CREATE (TCU)-[:contains]->(TCU_dh)
CREATE (TCU_k9:Node {name: 'K_9'})	CREATE (TCU)-[:contains]->(TCU_k9)
CREATE (TCU_k_pr_10:Node {name: 'K_pr_10'})	CREATE (TCU)-[:contains]->(TCU_k_pr_10)
CREATE (TCU_aes128_2:Node {name: 'AES128 CMAC'})	CREATE (TCU)-[:contains]->(TCU_aes128_2)
CREATE (TCU_hmac:Node {name: 'HMAC SHA256'})	CREATE (TCU)-[:contains]->(TCU_hmac)
CREATE (TCU_sha:Node {name: 'SHA384'})	CREATE (TCU)-[:contains]->(TCU_sha)
CREATE (TCU_rsa:Node {name: 'RAS2048'})	CREATE (TCU)-[:contains]->(TCU_rsa)
CREATE (TCU_k_pb_13:Node {name: 'K_pb_13'})	CREATE (TCU)-[:contains]->(TCU_k_pb_13)
CREATE (TCU_k8:Node {name: 'K_8'})	CREATE (TCU)-[:contains]->(TCU_k8)
CREATE (TCU_k6:Node {name: 'K_6'})	CREATE (TCU)-[:contains]->(TCU_k6)
CREATE (TCU_k_pb_7:Node {name: 'K_pb_7'})	CREATE (TCU)-[:contains]->(TCU_k_pb_7)
CREATE (TCU_k_pb_11:Node {name: 'K_pb_11'})	CREATE (TCU)-[:contains]->(TCU_k_pb_11)
CREATE (TCU_k_pb_12:Node {name: 'K_pb_12'})	CREATE (TCU)-[:contains]->(TCU_k_pb_12)
CREATE (TCU_k_pr_11:Node {name: 'K_pr_11'})	CREATE (TCU)-[:contains]->(TCU_k_pr_11)
CREATE (TCU_k_pr_7:Node {name: 'K_pr_7'})	CREATE (TCU)-[:contains]->(TCU_k_pr_7)
	
CREATE (Server_src:Node {name: 'Secure Remote Communication'})	CREATE (Server)-[:contains]->(Server_src)
CREATE (Server_gspfssu:Node {name: 'Generate SW for Secure SW Update'})	CREATE (Server)-[:contains]->(Server_gspfssu)
CREATE (Server_k17:Node {name: 'K_17'})	CREATE (Server)-[:contains]->(Server_k17)
CREATE (Server_tls:Node {name: 'TLS1.2'})	CREATE (Server)-[:contains]->(Server_tls)
CREATE (Server_aes_1:Node {name: 'AES128 CMAC'})	CREATE (Server)-[:contains]->(Server_aes_1)
CREATE (Server_k_pb_16:Node {name: 'K_pb_16'})	CREATE (Server)-[:contains]->(Server_k_pb_16)
CREATE (Server_k_pr_15:Node {name: 'K_pr_15'})	CREATE (Server)-[:contains]->(Server_k_pr_15)
CREATE (Server_cert:Node {name: 'Certificate'})	CREATE (Server)-[:contains]->(Server_cert)
CREATE (Server_cl:Node {name: 'Cryptolib'})	CREATE (Server)-[:contains]->(Server_cl)
CREATE (Server_k_pb_15:Node {name: 'K_pb_15'})	CREATE (Server)-[:contains]->(Server_k_pb_15)
CREATE (Server_k_pr_18:Node {name: 'K_pr_18'})	CREATE (Server)-[:contains]->(Server_k_pr_18)
CREATE (Server_k_pb_18:Node {name: 'K_pb_18'})	CREATE (Server)-[:contains]->(Server_k_pb_18)
CREATE (Server_rsa:Node {name: 'RSA2048'})	CREATE (Server)-[:contains]->(Server_rsa)
CREATE (Server_sha:Node {name: 'SHA384'})	CREATE (Server)-[:contains]->(Server_sha)
CREATE (Server_aes_2:Node {name: 'AES256 GCM'})	CREATE (Server)-[:contains]->(Server_aes_2)
CREATE (Server_dh:Node {name: 'DH'})	CREATE (Server)-[:contains]->(Server_dh)
CREATE (Server_k_pb_14:Node {name: 'K_pb_14'})	CREATE (Server)-[:contains]->(Server_k_pb_14)
CREATE (Server_k_pr_14:Node {name: 'K_pr_14'})	CREATE (Server)-[:contains]->(Server_k_pr_14)
	
	
	
	
CREATE (ECU_sum)-[:explicit]->(ECU_ssu)	
CREATE (ECU_sum)-[:explicit]->(ECU_sb)	
CREATE (ECU_ds)-[:explicit]->(ECU_sa)	
CREATE (ECU_ds)-[:explicit]->(ECU_sb)	
CREATE (ECU_ivc)-[:explicit]->(ECU_sb)	
CREATE (ECU_ivc)-[:explicit]->(ECU_soc)	
CREATE (ECU_ssu)-[:explicit]->(ECU_sa)	
CREATE (ECU_ssu)-[:explicit]->(ECU_cl)	
CREATE (ECU_soc)-[:explicit]->(ECU_cl)	
CREATE (ECU_sb)-[:explicit]->(ECU_cl)	
CREATE (ECU_sa)-[:explicit]->(ECU_cl)	
CREATE (ECU_cl)-[:explicit]->(ECU_aes1)	
CREATE (ECU_cl)-[:explicit]->(ECU_rsa)	
CREATE (ECU_cl)-[:explicit]->(ECU_hmac)	
CREATE (ECU_cl)-[:explicit]->(ECU_aes2)	
CREATE (ECU_aes1)-[:explicit]->(ECU_k1)	
CREATE (ECU_aes1)-[:explicit]->(ECU_k5)	
CREATE (ECU_rsa)-[:explicit]->(ECU_k_pb_2)	
CREATE (ECU_rsa)-[:explicit]->(ECU_k_pr_2)	
CREATE (ECU_hmac)-[:explicit]->(ECU_k3)	
CREATE (ECU_aes2)-[:explicit]->(ECU_k4)	
CREATE (ECU_k1)-[:secure_boot]->(ECU_k_pr_2)	
CREATE (ECU_k5)-[:secure_boot]->(ECU_k_pr_2)	
CREATE (ECU_k_pb_2)-[:secure_boot]->(ECU_k_pr_2)	
CREATE (ECU_k3)-[:secure_boot]->(ECU_k_pr_2)	
CREATE (ECU_k4)-[:secure_boot]->(ECU_k_pr_2)	
CREATE (ECU_k1)-[:secure_access]->(ECU_k4)	
CREATE (ECU_k5)-[:secure_access]->(ECU_k4)	
CREATE (ECU_k_pb_2)-[:secure_access]->(ECU_k4)	
CREATE (ECU_k3)-[:secure_access]->(ECU_k4)	
CREATE (ECU_k_pr_2)-[:secure_access]->(ECU_k4)	
CREATE (ECU_ssu)-[:functional_dependency]->(ECU_k5)	
CREATE (ECU_sb)-[:functional_dependency]->(ECU_k_pr_2)	
CREATE (ECU_sb)-[:functional_dependency]->(ECU_k3)	
CREATE (ECU_soc)-[:functional_dependency]->(ECU_k1)	
CREATE (ECU_sa)-[:functional_dependency]->(ECU_k4)	
	
	
CREATE (TCU_ssu)-[:explicit]->(TCU_src)	
CREATE (TCU_ssu)-[:explicit]->(TCU_sa)	
CREATE (TCU_ssu)-[:explicit]->(TCU_cl)	
CREATE (TCU_sb)-[:explicit]->(TCU_cl)	
CREATE (TCU_soc)-[:explicit]->(TCU_cl)	
CREATE (TCU_src)-[:explicit]->(TCU_tls)	
CREATE (TCU_src)-[:explicit]->(TCU_cl)	
CREATE (TCU_sa)-[:explicit]->(TCU_cl)	
CREATE (TCU_tls)-[:explicit]->(TCU_cl)	
CREATE (TCU_tls)-[:explicit]->(TCU_cert)	
CREATE (TCU_cert)-[:explicit]->(TCU_cl)	
CREATE (TCU_cl)-[:explicit]->(TCU_dh)	
CREATE (TCU_cl)-[:explicit]->(TCU_aes256)	
CREATE (TCU_cl)-[:explicit]->(TCU_aes128_1)	
CREATE (TCU_cl)-[:explicit]->(TCU_aes128_2)	
CREATE (TCU_cl)-[:explicit]->(TCU_hmac)	
CREATE (TCU_cl)-[:explicit]->(TCU_sha)	
CREATE (TCU_cl)-[:explicit]->(TCU_rsa)	
CREATE (TCU_dh)-[:explicit]->(TCU_k_pb_10)	
CREATE (TCU_dh)-[:explicit]->(TCU_k_pr_10)	
CREATE (TCU_aes128_1)-[:explicit]->(TCU_k9)	
CREATE (TCU_aes128_2)-[:explicit]->(TCU_k8)	
CREATE (TCU_hmac)-[:explicit]->(TCU_k6)	
CREATE (TCU_rsa)-[:explicit]->(TCU_k_pb_13)	
CREATE (TCU_rsa)-[:explicit]->(TCU_k_pr_7)	
CREATE (TCU_rsa)-[:explicit]->(TCU_k_pb_7)	
CREATE (TCU_rsa)-[:explicit]->(TCU_k_pb_11)	
CREATE (TCU_rsa)-[:explicit]->(TCU_k_pb_12)	
CREATE (TCU_rsa)-[:explicit]->(TCU_k_pr_11)	
CREATE (TCU_ssu)-[:functional_dependency]->(TCU_k_pb_13)	
CREATE (TCU_sb)-[:functional_dependency]->(TCU_k6)	
CREATE (TCU_sb)-[:functional_dependency]->(TCU_k_pr_7)	
CREATE (TCU_soc)-[:functional_dependency]->(TCU_k8)	
CREATE (TCU_src)-[:functional_dependency]->(TCU_k_pr_10)	
CREATE (TCU_src)-[:functional_dependency]->(TCU_sha)	
CREATE (TCU_src)-[:functional_dependency]->(TCU_dh)	
CREATE (TCU_src)-[:functional_dependency]->(TCU_k_pr_11)	
CREATE (TCU_src)-[:functional_dependency]->(TCU_k_pb_12)	
CREATE (TCU_sa)-[:functional_dependency]->(TCU_k9)	
CREATE (TCU_k_pb_10)-[:secure_boot]->(TCU_k_pr_7)	
CREATE (TCU_k_pb_10)-[:secure_boot]->(TCU_k_pr_11)	
CREATE (TCU_k_pr_10)-[:secure_boot]->(TCU_k_pb_10)	
CREATE (TCU_k_pr_10)-[:secure_boot]->(TCU_k_pr_7)	
CREATE (TCU_k8)-[:secure_boot]->(TCU_k_pr_7)	
CREATE (TCU_k6)-[:secure_boot]->(TCU_k_pr_7)	
CREATE (TCU_k_pb_7)-[:secure_boot]->(TCU_k_pr_7)	
CREATE (TCU_k_pb_11)-[:secure_boot]->(TCU_k_pr_7)	
CREATE (TCU_k9)-[:secure_boot]->(TCU_k_pr_7)	
CREATE (TCU_k_pb_13)-[:secure_boot]->(TCU_k_pr_7)	
CREATE (TCU_k_pb_12)-[:secure_boot]->(TCU_k_pr_7)	
CREATE (TCU_k_pb_12)-[:secure_boot]->(TCU_k_pb_11)	
CREATE (TCU_k_pr_11)-[:secure_boot]->(TCU_k_pb_11)	
CREATE (TCU_k_pr_11)-[:secure_boot]->(TCU_k_pr_7)	
	
	
CREATE (Server_src)-[:explicit]->(Server_cl)	
CREATE (Server_gspfssu)-[:explicit]->(Server_cl)	
CREATE (Server_aes_1)-[:explicit]->(Server_k17)	
CREATE (Server_tls)-[:explicit]->(Server_cl)	
CREATE (Server_tls)-[:explicit]->(Server_cert)	
CREATE (Server_cert)-[:explicit]->(Server_cl)	
CREATE (Server_cl)-[:explicit]->(Server_sha)	
CREATE (Server_cl)-[:explicit]->(Server_aes_2)	
CREATE (Server_cl)-[:explicit]->(Server_dh)	
CREATE (Server_cl)-[:explicit]->(Server_rsa)	
CREATE (Server_cl)-[:explicit]->(Server_aes_1)	
CREATE (Server_rsa)-[:explicit]->(Server_k_pb_16)	
CREATE (Server_rsa)-[:explicit]->(Server_k_pr_15)	
CREATE (Server_rsa)-[:explicit]->(Server_k_pb_15)	
CREATE (Server_rsa)-[:explicit]->(Server_k_pr_18)	
CREATE (Server_rsa)-[:explicit]->(Server_k_pb_18)	
CREATE (Server_dh)-[:explicit]->(Server_k_pb_14)	
CREATE (Server_dh)-[:explicit]->(Server_k_pr_14)	
CREATE (Server_src)-[:functional_dependency]->(Server_sha)	
CREATE (Server_src)-[:functional_dependency]->(Server_aes_2)	
CREATE (Server_src)-[:functional_dependency]->(Server_k_pb_16)	
CREATE (Server_gspfssu)-[:functional_dependency]->(Server_k_pb_18)	
CREATE (Server_gspfssu)-[:functional_dependency]->(Server_k17)	
CREATE (Server_gspfssu)-[:functional_dependency]->(Server_k_pr_15)	
CREATE (Server_k_pb_15)-[:secure_boot]->(Server_k_pr_15)	
CREATE (Server_k_pb_15)-[:secure_boot]->(Server_k_pb_16)	
CREATE (Server_k_pb_18)-[:secure_boot]->(Server_k_pr_18)	
CREATE (Server_k_pb_14)-[:secure_boot]->(Server_k_pr_15)	
CREATE (Server_k_pb_14)-[:secure_boot]->(Server_k_pr_14)	
	
	
CREATE (ECU_k1)-[:shared_keys]->(TCU_k8)	
	
	
CREATE (TCU_k8)-[:shared_keys]->(ECU_k1)	
	
	
CREATE (ECU_k5)-[:shared_keys]->(Server_k17)	
	
	
CREATE (Server_k17)-[:shared_keys]->(ECU_k5)	
	
	
CREATE (TCU_k_pb_10)-[:communication_dependency]->(Server_k_pr_14)	
CREATE (TCU_k_pb_12)-[:shared_keys]->(Server_k_pb_16)	
CREATE (TCU_k_pb_13)-[:shared_keys]->(Server_k_pr_18)	
	
	
CREATE (Server_k_pb_14)-[:communication_dependency]->(TCU_k_pb_10)	
CREATE (Server_k_pb_16)-[:shared_keys]->(TCU_k_pb_12)	
CREATE (Server_k_pr_18)-[:shared_keys]->(TCU_k_pb_13)	
;	
